import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { fetchCoffeeShopsData } from "../lib/coffee-stores";

import Banner from "../components/banner/banner";
import Card from "../components/card/card";

export async function getStaticProps(context) {
  const data = await fetchCoffeeShopsData();
  console.log(data)
  return {
    props: { coffeeStores: data }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const handleBannerBtnOnClick = () => {
    console.log("hi banner btn");
  };
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText={"View Coffee shop nearby"}
          handleOnClick={handleBannerBtnOnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero-image"
          />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                const imgUrl = `${coffeeStore.imgData.prefix}original${coffeeStore.imgData.suffix}`;
               
                return (
                <Card
                  key={coffeeStore.fsq_id}
                  className={styles.card}
                  name={coffeeStore.name}
                  imgUrl={imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                  href={`/coffee-store/${coffeeStore.fsq_id}`}
                />
              )})}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
